### ISSUE TITLE
Context.uri is misleading

### ISSUE THREAD

**Issue by hjr3** [Ogeon/rustful#115]
I think https://github.com/Ogeon/rustful/blob/master/src/context/mod.rs#L148 is misleading.

According to https://tools.ietf.org/html/rfc3986 the URI contains something like 
```
scheme:[//[user:password@]host[:port]][/]path[?query][#fragment]
```
In Rustful, calling `context.uri` only gives the path. Should we consider renaming that `uri` to `path`?

**Comment by Ogeon** [comment]
Yeah, that's probably a good Idea. The `Uri` type should also be renamed. Thanks for pointing it out :+1:
