### ISSUE TITLE
Remove support for rustc-serialize

### ISSUE THREAD

**Issue by Ogeon** [Ogeon/rustful#123]
`rustc-serialize` [has been deprecated](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485) so there's no longer any good reasons to maintain built-in support for it.

**Comment by xliiv** [comment]
By "remove" you mean "remove all references to rustc-serialize until test passes"?
If so here's the quick version of that:
https://github.com/Ogeon/rustful/compare/master...xliiv:rustc-serialize-%23123?expand=1

What do you think, would you like to spare somehow `examples/todo.rs`?

**Comment by Ogeon** [comment]
Oh my, I thought I answered this via email! I'm so sorry @xliiv, I didn't intend to leave you hanging for a month.

What you did looks good, but I would like to keep the todo example. It may at least serve as an example of how to convert to serde. Do you feel like picking this up again?

**Comment by xliiv** [comment]
Hanging was ok, i've just moved on. ;)
So @Ogeon, you'd like to convert the todo example to serde and rest is ok?

**Comment by Ogeon** [comment]
Yep, that should be enough. No need to replace the methods, since serde JSON should have tools that covers those use cases.

**Comment by xliiv** [comment]
I'll giva a try tomorrow.. .

**Comment by Ogeon** [comment]
Nice! Thank you! Let me know if you change your mind. :slightly_smiling_face:

**Comment by xliiv** [comment]
I changed my mind. I did some work today. ;)
Take a look at the newest version, with reverted example: todo
https://github.com/Ogeon/rustful/compare/master...xliiv:rustc-serialize-%23123?expand=1
If it's ok or close to ok, i can do pull-request.

**Comment by Ogeon** [comment]
Heh, by changing your mind I meant not continuing, but I guess this counts as well

**Comment by Ogeon** [comment]
That's great! A very clean and straight forward port! :+1:
