### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by whiplash** [Ogeon/rustful#24]
I'm trying to compile the example with `rustc 1.0.0-nightly (d8be84eb4 2015-03-29) (built 2015-03-29)` and I get so many errors it would be embarrassing to show :)

**Comment by whiplash** [comment]
I guess what I mean is: should it be working with rust 1.0.0?

**Comment by Ogeon** [comment]
2015-03-29? That was some time ago. You can go back to a previous commit and hope there will be a compatible one, but your best bet would be to go with the latest nightly or beta.

**Comment by whiplash** [comment]
:+1:

**Comment by whiplash** [comment]
just updated my rust version.
Still getting compiler error (only on `cookie`).

`Compiling cookie v0.1.18
/Users/mfirry/.cargo/registry/src/github.com-1ecc6299db9ec823/cookie-0.1.18/src/lib.rs:56:20: 56:39 error: unresolved name url::percent_decode
/Users/mfirry/.cargo/registry/src/github.com-1ecc6299db9ec823/cookie-0.1.18/src/lib.rs:56         let name = url::percent_decode(name.as_bytes());`

**Comment by Ogeon** [comment]
That would be an issue with the [cookie library](https://github.com/alexcrichton/cookie-rs). Seems like the beta is the most promising option at the moment, unless a patch comes soon.

**Comment by whiplash** [comment]
Ok. Should I explicitly depend on the beta version then?

**Comment by Ogeon** [comment]
I bumped into this myself with an other project and it seems like they decided to remove that function from the url library, so things are simply broken for now, unless you override the dependencies somehow (I think you can edit your `Cargo.lock` and use the previous version). Seems like we have to wait while things caches up.

**Comment by whiplash** [comment]
Thanks!

**Comment by Ogeon** [comment]
Things should build with the beta now. Remember to run `cargo update` to get the latest libraries.

**Comment by whiplash** [comment]
Working now. Thanks!
