### ISSUE TITLE
Windows compile requires OpenSSL

### ISSUE THREAD

**Issue by Zarathustra30** [Ogeon/rustful#53]
Build fails on Windows 7 with the "ssl" feature enabled, due to lack of OpenSSL.

While Rustful is not at fault, there should be a note in the README stating that OpenSSL is a dependency.

Furthermore, it would be nice (but not necessary) to include OpenSSL installation instructions. Unfortunately, the instructions found in the [rust-openssl](https://github.com/sfackler/rust-openssl) repository didn't work, so I do not know any install procedure.

**Comment by Ogeon** [comment]
Yeah, a note about the dependency is a good idea. I'm not really a Windows guy, so I don't know if my method is correct, but I guess I could write something based on what I do in `appveyor.yml`.

**Comment by Ogeon** [comment]
Do you think the current notice is enough?

**Comment by Zarathustra30** [comment]
The current notice is excellent. Thank you. I thought I put something in my close message, but I guess I didn't.

**Comment by Ogeon** [comment]
Alright :smile:
