### ISSUE TITLE
Add shared plugin context

### ISSUE THREAD

**Issue by Ogeon** [Ogeon/rustful#6]
Add a "request local" storage for plugins through which they can communicate and share data. The context will follow the plugin pipeline from the request plugins to the response plugins and be available to the handler.

### A Few Storage Alternatives

* Use an [`AnyMap`](https://github.com/chris-morgan/anymap) and let the plugins add custom entries. Prevents name collisions between plugins and allows anything to be stored, but requires indirections and allocations.

* Use a `HashMap`, or similar, with a predefined storage type. Can be done with few allocations, but not that flexible and name collisions will become a problem.

* Use a `HashMap`, or similar, with a predefined storage trait. Suffers from the other alternatives, but gives more or less the same flexibility as the `AnyMap` when it comes to what can be stored.

The first alternative seems like the most convenient for the developers. It will also make the storage more predictable by using the type as the key.

### Pipeline Sketch

1. ServerInstance: Create empty plugin context.
2. ServerInstance: For plugin in request plugins: Input request + plugin context.
3. ServerInstance: Store plugin context in response.
4. Handler: Read, add or manipulate plugin context entries through response.
5. Handler: Write to client.
  * Response: For plugin in response plugins: Input data + plugin context.
6. _Repeat 4 and/or 5 or go to 7._
7. Response: For plugin in response plugins (reversed): Input data + plugin context.

Any ideas or enhancements are appreciated.

**Comment by DisruptiveMind** [comment]
I am interested in this feature as well. 

I was planning to approach using a Chain of plugins/middleware to call a sequence and then handle the final handler when building the TreeRouter.

Using your example...without being idiomatic here so bare with me

```rust

fn say_hello(context: Context, response: Response) {
    //Get the value of the path variable `:person`, from below.
    let person = match context.variables.get("person") {
        Some(name) => &name[],
        None => "stranger"
    };

    //Use the value of the path variable to say hello.
    try_send!(response.into_writer(), format!("Hello, {}!", person), "saying hello");
}

// Note the next: Chain parameter
fn server_name(context: Context, response: Response, chain: Chain) {
    // Set header...
    response.set_header(hyper::header::Server(self.server.clone())))
    
    chain.next()
}

// Checks for a valid user in the context
fn valid_user(context: Context, response: Response, chain: Chain) {
    // plugin/middleware data is assigned/retrieved through context.env
    match context.env.get("user") {
      Some => chain.next()
      None => chain.abort()
    }
}

⋮

let mut baseChain: Chain = Chain::new(server_name)
baseChain.append(valid_user)

TreeRouter::new(): {
  //Handle requests for root...
  "/" => Get: say_hello,

  //...and one level below.
  //`:person` is a path variable and it will be accessible in the handler.
  "/:person" => Get: base_chain.handle(say_hello)
}
```

**Comment by Ogeon** [comment]
I think I get your idea. You want to insert a sort of handler sequence in the router to isolate parts of the logic, right? That's absolutely possible right now. `Chain` can implement `Handler` and maybe let the inner links borrow the context and the response. That's an interesting addition and this "plugin context" could be used to tie the links together.

**Comment by DisruptiveMind** [comment]
That's correct so chains can also be composed on different endpoints as well.

Have you considered subroutes or "sub trees" as well?

**Comment by Ogeon** [comment]
I have. That's one of the reasons why I made the router generic. I want people to be able to replace `TreeRouter` with their own solution, which may or may not include subrouters :) I would also like to extend the macro to make it possible to add subrouters that way. I haven't decided if I want to add it to the `Router` trait and make it a requirement, but I have considered it.

**Comment by Ogeon** [comment]
...or did you mean subroutes as in `a/b/c` and `a/b/d`? That's already possible, but the hello world example doesn't use it. It can be seen [here](http://ogeon.github.io/rustful/doc/rustful/router/index.html).

**Comment by DisruptiveMind** [comment]
I was thinking more in terms of creating the subroutes within the insert_routes macro as well.

In terms of "plugin context" is this the same as the context in the handler or completely different?

**Comment by Ogeon** [comment]
Allright :) Well, as I wrote, it's already implemented, but not used in the hello world example.

The "plugin context" is different. It's for communication with and between context plugins and response plugins. You can find their traits in the documentation and there is also an example for them. I do actually think that your chain would work better with its own way of propagating information, since this context will be tightly integrated into the `Response` structure.
