### ISSUE TITLE
Remove the logging system in favor of the Log crate

### ISSUE THREAD

**Issue by Ogeon** [Ogeon/rustful#71]
[Log](https://crates.io/crates/log) has basically the same purpose as the loging system in the server, namely a common, user defined logger. I see no reason to keep the logging system around when Log is widely adopted and has an even more convenient API.

What should be done is:

 * Remove the `log` module.
 * Remove the presence of the logger from the server, every context and every response type.
 * Include Log as a dev-dependency and use it in examples.

The reason for using it in the examples is that I don't want to promote `println!` logging. Forced log printing is nasty and we don't want to look nasty, do we?

It's not the smallest task, but it shouldn't be too complicated.

**Comment by kvikas** [comment]
I still have to fix documentation on this. Can you review if this is what your plan was? Also this will break any client already using `log` module or `context.log`. Was this intended?

**Comment by Ogeon** [comment]
Yes, and that's ok. It will be released under a new 0.X version.
