### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by flosse** [Ogeon/rustful#80]
Would you mind to add a changelog.md ?

**Comment by Ogeon** [comment]
Sure, that sounds like a good idea. I'll see what I can come up with, but I'm leaning towards a script that filters out and parses Homu's commits.

**Comment by Ogeon** [comment]
Alright, now there's a [changelog](https://github.com/Ogeon/rustful/blob/master/CHANGELOG.md). It will be updated on each release.
